# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: maven-helper-script 0.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "maven-helper-script"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["benkiefer"]
  s.date = "2015-04-30"
  s.description = "Execute your complex maven commands faster with the shortened helper syntax. See the rdoc for more details and examples."
  s.email = "ben.a.kiefer@gmail.com"
  s.executables = ["m"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/m",
    "lib/argument_parser.rb",
    "lib/configuration_checker.rb",
    "lib/invalid_command_exception.rb",
    "lib/project_home_finder.rb",
    "lib/script_runner.rb",
    "maven-helper-script.gemspec"
  ]
  s.homepage = "http://benkiefer.github.io/maven-helper-script"
  s.required_ruby_version = Gem::Requirement.new("~> 2.2")
  s.rubygems_version = "2.4.6"
  s.summary = "Ruby gem to simplify maven command execution"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>, ["~> 4.2"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.2"])
    else
      s.add_dependency(%q<rdoc>, ["~> 4.2"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<rspec>, ["~> 3.2"])
    end
  else
    s.add_dependency(%q<rdoc>, ["~> 4.2"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<rspec>, ["~> 3.2"])
  end
end

